# -*- coding: utf-8 -*-
{
    'name': "Education Core",
    'summary': """
        Education Core""",
    'description': """
       Education Core
    """,
    'description': """Education Core for School College University""",
    'category': 'Website/eLearning',
    'author': "Alhaditech",
    'price': 1299, 'currency': 'USD',
    'license': 'AGPL-3',
    'version': '16.0.4',
    'website': "https://www.alhaditech.com",
    'images': ['static/description/background.png'],
    # any module necessary for this one to work correctly
    'depends': ['base', 'hr', 'stock', 'product', 'account', 'uom'],
    # always loaded
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/record_rule.xml',
        'demo/demo.xml',
        'data/sequence.xml',
        'views/scripts.xml',
        'views/navbar.xml',
        'views/portal_side_panel.xml',
        'views/portal_ui_settings.xml',
        'views/edu_config.xml',
        'views/student.xml',
        'views/lecturer.xml',
        'views/dept.xml',
        'views/college.xml',
        'views/course.xml',
        'views/program.xml',
        'views/academic_year.xml',
        'views/attendance.xml',
        'views/attendance_correction.xml',
        'views/course_offerings.xml',
        'views/registration.xml',
        'views/lecturer_note.xml',
        'views/class_section.xml',
        'views/class_room.xml',
        'views/lab.xml',
        'views/time_slot.xml',
        'views/class_timetable.xml',
        'views/scholarship.xml',
        'wizard/wizard_course_selection.xml',
        'wizard/wizard_report_timetable.xml',
        'wizard/wizard_report_attendance.xml',
        'wizard/wizard_fee.xml',
        'reports/timetable_report.xml',
        'reports/attendance_report.xml',
        'reports/membership_card.xml',
        'views/student_dashboard.xml',
        'views/lecture_notes.xml',
        'views/attendance_portal.xml',
        'views/attendance_details.xml',
        'views/timetable_portal.xml',
        'views/student_profile_portal.xml',
        'views/assignment_submission.xml',
        'views/assignments.xml',
        'views/book.xml',
        'views/issue_book.xml',
        'views/member.xml',
        'views/author.xml',
        'views/book_genre.xml',
        'views/publishers.xml',
        'views/menu.xml',
        'views/page.xml',
        'views/unauthorized.xml',
        'views/library_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'aht_education_core/static/src/css/library_dashboard.css',
            'aht_education_core/static/src/css/lib/nv.d3.css',
            'aht_education_core/static/src/js/library_dashboard.js',
            'aht_education_core/static/src/js/lib/d3.min.js',
            'aht_education_core/static/src/xml/library_dashboard.xml',
        ],
    },
    # only loaded in demonstration mode
    'demo': [
        # 'demo/demo.xml',
    ],
}
