# -*- coding: utf-8 -*-
{
    'name': "Ecommerce Website Sale",
    'summary': """ """,
    'description': """ """,
    'author': "My Company",
    'license': 'LGPL-3',
    'website': "http://www.yourcompany.com",
    'category': 'Human Resources',
    'version': '15.0.0',
    'depends': ['website_sale', 'portal', 'website', 'stock', 'studio_model_type_change', 'website_sale_delivery'],
    'data': [
        'security/ir.model.access.csv',
        'report/sale_order_report.xml',
        'data/website_menu.xml',
        'data/website_footer_menu.xml',
        'views/website_footer_menu.xml',
        'views/template.xml',
        'views/footer_tem.xml',
        'views/shop_page.xml',
        # 'views/shop_page_2.xml',
        'views/home_page.xml',
        'views/snippet.xml',
        'views/search_radio_page.xml',
        'views/header.xml',
        'views/add_cart_template.xml',
        'views/retrofit_radio_temp1.xml',
        'views/station_search_template.xml',
        'views/product_info_page.xml',
        'views/cart_shop_template.xml',
        'views/address_template.xml',
        'views/footer_impressum.xml',
        'views/footer_daten.xml',
        'views/footer_installation.xml',
        'views/footer_agb.xml',
        'views/product_views.xml',
        'views/confirmation_page.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'website_ecom_custom/static/src/css/payment_wonderbar.scss',
            'website_ecom_custom/static/src/css/website_sale.css',
            'website_ecom_custom/static/src/css/search_radio.css',
            'website_ecom_custom/static/src/css/home_page.css',
            'website_ecom_custom/static/src/css/footer_impressum.css',
            'website_ecom_custom/static/src/css/footer_agb.css',
            'website_ecom_custom/static/src/css/footer_installation.css',
            'website_ecom_custom/static/src/css/footer_daten.css',
            'website_ecom_custom/static/src/css/product_info_page.css',
            'website_ecom_custom/static/src/css/retrofit_radio.css',
            'website_ecom_custom/static/src/css/shop_page.css',
            # 'website_ecom_custom/static/src/css/shop_page2.css',
            'website_ecom_custom/static/src/css/add_to_cart.css',
            'website_ecom_custom/static/src/css/address_temp.css',
            'website_ecom_custom/static/src/css/header.css',
            'website_ecom_custom/static/src/css/express_paypal_checkout.scss',

            'website_ecom_custom/static/src/js/update_cart.js',
            'website_ecom_custom/static/src/css/product_template.css',
            'website_ecom_custom/static/src/css/cart_shop.css',
            'website_ecom_custom/static/src/js/payment_wonderbar.js',
            'website_ecom_custom/static/src/js/color_change.js',
            'website_ecom_custom/static/src/js/product_search.js',
            'website_ecom_custom/static/src/js/variant_mixin.js',
            'website_ecom_custom/static/src/js/wunderbar_shop_product_checkout.js',
            'website_ecom_custom/static/src/js/wunderbar_shopcart_payment.js',
            'website_ecom_custom/static/src/js/wunderbar_checkout_form.js',

        ],
    },
}
