{
    'name': 'hotel management',
    'version': '16.0.1',
    'summary': 'hotel management',
    'sequence': 10,
    'description': """
""",
    'category': '',
    'website': '',
    'depends': ['base', 'mail', 'website_sale'],
    'data': [
        'security/ir.model.access.csv',
        'views/booking_form_views.xml',
        'views/room_types_views.xml',
        'views/room_number_views.xml',
        'views/booking_history_views.xml',
        'views/res.partner_views.xml',
        'views/main_template.xml',
        'views/booking_form_template.xml',
        'views/customer_form_template.xml',
        'views/hotel_portal_template.xml',
        'data/seq_booking_form_data.xml',
        'data/seq_booking_history_data.xml',
        'report/booking_report.xml',
        'wizard/confirm_report_views.xml',
        'security/hotel_security.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
