{
    'name': 'Meeting Rooms Management',
    'version': '1.12',
    'category': 'Tools',
    'summary': 'Manage meeting rooms and bookings',
    'description': 'Module to manage meeting rooms and bookings',
    'author': 'Loai Souboh',
    'website': 'https://www.yourcompany.com',
    'depends': ['base', 'mail', 'website'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/booking_views.xml',
        'views/meeting_room_views.xml',
        'views/res_users_views.xml',
        'views/email_templates.xml',
        'views/menu_views.xml',
        'data/scheduled_actions.xml',
        'views/templates.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
